services:

    # Symfony apache project container
    php:
        build:
          context: ..
          dockerfile: ./docker/php/Dockerfile
        volumes:
          - ..:/var/www/symfony
        container_name: symfony_php
        ports:
          - "9000:9000"

      # Nginx service
    nginx:
        image: nginx:alpine
        container_name: symfony_nginx
        ports:
          - "8000:80"
        volumes:
          - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
         - php
