name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - uses: php-actions/composer@v6
      - uses: php-actions/phpstan@v3
        with:
          path: src/
      - name: Run test suite
        run: vendor/bin/phpunit
        with:
          php-version: 8.3